global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'laravel'
    static_configs:
      - targets: ['laravel_app:9000']
    metrics_path: '/metrics'

  - job_name: 'redis'
    static_configs:
      - targets: ['laravel_redis:6379'] 